In [1]:
from tensorflow.keras.preprocessing.image import ImageDataGenerator


In [2]:
train_datagen = ImageDataGenerator(rescale=1./255, zoom_range=0.25, horizontal_flip=True,vertical_flip=False,width_shift_range=0.2)

In [3]:
test_datagen = ImageDataGenerator(rescale=1./255)

In [4]:
img_width = 128
img_height = 128

In [5]:
x_train = train_datagen.flow_from_directory(r'C:\Users\Srikanth\Desktop\python\CATS AND DOGS\dataset\training_set',target_size=(img_width,img_height), class_mode='categorical', batch_size=100)

Found 1000 images belonging to 2 classes.


In [6]:
x_test = test_datagen.flow_from_directory(r'C:\Users\Srikanth\Desktop\python\CATS AND DOGS\dataset\test_set',target_size=(img_width,img_height), class_mode='categorical', batch_size=100)

Found 300 images belonging to 2 classes.


In [7]:
#to define linear initializations
from tensorflow.keras.models import Sequential
#convolution layer
from tensorflow.keras.layers import Convolution2D
#maxpooling layer
from tensorflow.keras.layers import MaxPooling2D
#flatten layer
from tensorflow.keras.layers import Flatten
#importing dense layers to create NN
from tensorflow.keras.layers import Dense

In [8]:
cg = Sequential()

In [9]:
cg.add(Convolution2D(32,(3,3),input_shape=(img_width,img_height,3),activation='relu')) #(32,(3,3)) FEATURE DETECTOR SIZE

In [10]:
cg.add(MaxPooling2D(pool_size=(2,2)))

In [11]:
cg.add(Flatten())

In [12]:
cg.output_shape

(None, 127008)

In [13]:
cg.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d (Conv2D)              (None, 126, 126, 32)      896       
_________________________________________________________________
max_pooling2d (MaxPooling2D) (None, 63, 63, 32)        0         
_________________________________________________________________
flatten (Flatten)            (None, 127008)            0         
Total params: 896
Trainable params: 896
Non-trainable params: 0
_________________________________________________________________


In [14]:
cg.add(Dense(units=300,kernel_initializer='random_uniform',activation='relu'))

In [15]:
cg.add(Dense(units=150,kernel_initializer='random_uniform',activation='relu'))

In [16]:
cg.add(Dense(units=2,kernel_initializer='random_uniform',activation='softmax'))

In [17]:
cg.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])

In [18]:
cg.fit_generator(x_train,steps_per_epoch=1000//100,epochs=20,validation_data=x_test,validation_steps=300//100)

C:\Users\Srikanth\anaconda3\lib\site-packages\tensorflow\python\keras\engine\training.py:1844: UserWarning: `Model.fit_generator` is deprecated and will be removed in a future version. Please use `Model.fit`, which supports generators.
  warnings.warn('`Model.fit_generator` is deprecated and '


Epoch 1/20
10/10 [==============================] - 59s 6s/step - loss: 1.1260 - accuracy: 0.5141 - val_loss: 0.6905 - val_accuracy: 0.5133
Epoch 2/20
10/10 [==============================] - 22s 2s/step - loss: 0.7076 - accuracy: 0.5239 - val_loss: 0.7208 - val_accuracy: 0.5000
Epoch 3/20
10/10 [==============================] - 23s 2s/step - loss: 0.7067 - accuracy: 0.5158 - val_loss: 0.6815 - val_accuracy: 0.5167
Epoch 4/20
10/10 [==============================] - 21s 2s/step - loss: 0.7000 - accuracy: 0.5390 - val_loss: 0.7444 - val_accuracy: 0.5000
Epoch 5/20
10/10 [==============================] - 22s 2s/step - loss: 0.7079 - accuracy: 0.5009 - val_loss: 0.6639 - val_accuracy: 0.6067
Epoch 6/20
10/10 [==============================] - 22s 2s/step - loss: 0.6752 - accuracy: 0.5728 - val_loss: 0.6570 - val_accuracy: 0.6100
Epoch 7/20
10/10 [==============================] - 22s 2s/step - loss: 0.6670 - accuracy: 0.5936 - val_loss: 0.6452 - val_accuracy: 0.6133
Epoch 8/20
10/10 [==

In [19]:
x_train.class_indices

{'cats': 0, 'dogs': 1}

In [20]:
cg.save('animal.h5')

In [21]:
import numpy as np
from tensorflow.keras.models import load_model
from tensorflow.keras.preprocessing import image

In [22]:
model=load_model('animal.h5') #  h5 deep learning model extension

In [23]:
img=image.load_img(r'C:\Users\Srikanth\Desktop\python\CATS AND DOGS\dataset\test_set\dogs\dog.4855.jpg', target_size=(128,128))

In [24]:
x=image.img_to_array(img)

In [25]:
x.shape

(128, 128, 3)

In [26]:
x=np.expand_dims(x,axis=0)

In [27]:
x.shape

(1, 128, 128, 3)

In [28]:
a=model.predict_classes(x)

C:\Users\Srikanth\anaconda3\lib\site-packages\tensorflow\python\keras\engine\sequential.py:450: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


In [29]:
a

array([1], dtype=int64)

In [30]:
index=['cats','dogs']

In [31]:
result=str(index[a[0]])

In [32]:
result

'dogs'

In [33]:
from sklearn.metrics import classification_report, confusion_matrix
Y_pred = model.predict_generator(x_test, 300 // 32+1)
y_pred = np.argmax(Y_pred, axis=1)
print('Confusion Matrix')
print(confusion_matrix(x_test.classes, y_pred))
print('Classification Report')
target_names = ['cats','dogs']
print(classification_report(x_test.classes, y_pred, target_names=target_names))

C:\Users\Srikanth\anaconda3\lib\site-packages\tensorflow\python\keras\engine\training.py:1905: UserWarning: `Model.predict_generator` is deprecated and will be removed in a future version. Please use `Model.predict`, which supports generators.
  warnings.warn('`Model.predict_generator` is deprecated and '


Confusion Matrix
[[ 53  97]
 [ 38 112]]
Classification Report
              precision    recall  f1-score   support

        cats       0.58      0.35      0.44       150
        dogs       0.54      0.75      0.62       150

    accuracy                           0.55       300
   macro avg       0.56      0.55      0.53       300
weighted avg       0.56      0.55      0.53       300



In [34]:
target_names = []
for key in x_train.class_indices:
    target_names.append(key)
print(target_names)

['cats', 'dogs']


In [35]:
img=image.load_img(r'C:\Users\Srikanth\Desktop\python\dog1.jpg', target_size=(128,128))

In [36]:
x=image.img_to_array(img)

In [37]:
x.shape

(128, 128, 3)

In [38]:
x=np.expand_dims(x,axis=0)

In [39]:
x.shape

(1, 128, 128, 3)

In [40]:
a=model.predict_classes(x)

C:\Users\Srikanth\anaconda3\lib\site-packages\tensorflow\python\keras\engine\sequential.py:450: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


In [41]:
a

array([1], dtype=int64)

In [42]:
index=['cats','dogs']

In [44]:
result=str(index[a[0]])

In [45]:
result

'dogs'